language: java
sudo: false
env:
    global:
      #key for github
        - secure: "cmM+gGVeDgjsoDRPvVxDu09nbM/0Mxf8KcY4algwqF8HRR4VQ94vQd7XJx7mHdmJkaB4DUXSpeUuswAf40c9HiKB7Or+Ud97ZGfIcRC3AWaSsbR8MlKOruVFsYOeezbIzw1eygo5Ww3X/xE7tZk8gzk3ywIYkfwdK1h5HqWueMjq2SproDyWHqe82IL7ZzMgP74g4kBvHNM+m+3VqgctQI9UojlqUXWBbSGTCb2MnorJypy3+DNhgV2A6yRfSNtcUK9FyuGYHii8BveIqVFvL6BFKaMCy7EMhgKnI3Tse0VI5u0jMbH+fqIszmu/SbvhLQI+15AAXhSr3D6TCStmeamlpZzWe3F20sM5AtTGxdt5aJThqhfHT9VQ4gO6q06GAfK7mCuK59vHdXX+Zp4uXCdKu4qudJVEV2L6dGNDETYnx1R1Q0aWlachvsxpsKsSyk/JaWiXAPRmfhH4wKSjV2eOkBCTilGbIgb8PUIOlnsHpjBly9nqgpa2H28Vw2ojBxxXMRMO9FeWvmH3blvE1tBhN0QYs7JiB4JcyY9bM47BKaPvYARwu8nW/o8FmqOmm6eGlIVOwcp2Sale7m3Z2w4zalURC8GxIvQ45fAuGQRSV3jDASj8bowgbUkPHKTdOVaacggbdrxqEddGoUpGxLjG1msC6cvHvztjNmhRR5U="
        - environment=test

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script: mvn clean jacoco:prepare-agent install jacoco:report coveralls:report site -Denvironment=test
