name: CI

on:
  push:
    branches: [ develop ]

jobs:
  uild:
    name: Build and execute tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11

    - name: Run tests
      run: |
        mvn clean jacoco:prepare-agent install jacoco:report -P !build-extras
        mvn site -Djacoco.skip -DskipTests -P !build-extras

    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3

    - name: Send to sonarqube
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./target/site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ secrets.SIGNING_KEY }}
        passphrase: ${{ secrets.SIGNING_PASSWORD }}

    - name: Deploy to maven central
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      run: mvn deploy -P sign,build-extras --settings mvnsettings.xml -DskipTests
